workflows:
  element-ios:
    name: Element iOS Build
    environment:
      groups:
        - ios_signing_credentials
      vars:
        FLUTTER_VERSION: "3.16.9"
        XCODE_VERSION: "15.0"
        BUNDLE_ID: "io.element.elementX"
        BUILD_NUMBER: "1.11.25"

    scripts:
      - name: Verify project structure
        script: |
          echo "当前工作目录: $(pwd)"
          echo "目录内容:"
          ls -la
          if [ ! -f "pubspec.yaml" ]; then
            echo "错误：在根目录找不到 pubspec.yaml"
            find . -name pubspec.yaml -exec dirname {} \;
            exit 1
          fi

      - name: Setup Flutter
        script: |
          FLUTTER_PATH="${FLUTTER_ROOT:-$HOME/programs/flutter}"
          echo "Flutter 路径: $FLUTTER_PATH"
          
          flutter config --no-analytics
          flutter doctor -v
          
          if [ ! -f "pubspec.yaml" ]; then
            echo "自动创建 Flutter 项目结构..."
            flutter create . --org $BUNDLE_ID --platforms ios
          fi
          
          flutter clean
          flutter pub get

      - name: iOS Build
        script: |
          keychain initialize
          xcode-project use-profiles
          
          # 设置构建号
          agvtool new-version -all $BUILD_NUMBER
          
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER \
            --dart-define=FLAVOR=element \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your-team@example.com
